### ISSUE TITLE
Problems with Dockerfile instructions and alternatives

### ISSUE THREAD

**Issue by quinn-dev** [sleepdiary/dashboard#5]
First of all, there is one notable issue with the [`Dockerfile`](https://github.com/sleepdiary/dashboard/blob/70eb0ac160e0d9eb0f51603defc9236ea4dab31e/Dockerfile) itself: The following line has no recognizable use:
https://github.com/sleepdiary/dashboard/blob/b7ad5678a1bba6091d4ea3b8ac19929989383308/Dockerfile#L2

All it does is install `@vue/cli` (not the required `@vue/cli-service`) globally.
Since the package is neither required nor used, it can be removed safely (see #3).

---

Second, the current compilation instructions in the [`README`](https://github.com/sleepdiary/dashboard/blob/d98e67c75d92ba30631486a2199ad6fe64f4fd99/README.md) are incomplete.

Before running the container, the required node modules must be installed by running `yarn`.

Furthermore, when running the development environment, port 8080 needs to be exposed (`-p 8080:8080`), which isn't made clear in the current instruction:
https://github.com/sleepdiary/dashboard/blob/d98e67c75d92ba30631486a2199ad6fe64f4fd99/README.md#L12

---

Third, Docker is completely unnecessary for compilation. One can just run `yarn serve` or `yarn build` respectively after cloning the repository and installing the modules. I would advocate for prioritizing yarn-related instructions over Docker-related instructions. The Dockerfile may be kept around to accommodate specific workflows or could be removed entirely.

A PR implementing this can be found in #4.

**Comment by andrew-sayers** [comment]
There are several issues here.  Let's start with the easiest one and work our way up :)

You're right that a port (usually 8080) needs to be exposed.  I also forgot to add `-it` to that line, which makes vue's output much more readable.  Similar fixes might need to be copy/pasted into other repo's in this project - I'll look into it and let you know.

You're also right that node modules need to be installed, but not necessarily before running the container.  I've just changed the last line of my local `Dockerfile` to:

    CMD [ "sh", "-c", "yarn && yarn serve" ]

This seems to work, and isn't much redundant work in the circumstances.  I'd be interested to know your opinion, but it seems like a fairly uncontroversial upgrade.  Let me know, and I'll push something out tomorrow.

I probably left `@vue/cli` in because it was necessary to *create* the vue app in the first place, and there was no reason to take it out afterwards.  I can't immediately think of a reason to keep it in now everything's released, but I'd like to sleep on it first in case I'm forgetting something.

Moving on to Docker - sorry but the `Dockerfile`s stay as the default solution.  The `yarn` issue above is a good example - editing the `Dockerfile` to handle a new use case fixes the problem for everyone without having to make them change their workflow.  It also helps standardise the build process across the project.  For example, [the report](https://github.com/sleepdiary/report) is built in a completely different way, but the instructions are almost identical.  And [the library's `Dockerfile`](https://github.com/sleepdiary/library/blob/main/Dockerfile) ended up needing a bunch of weird packages in order to create a repeatable build, but the instructions are the same (albeit in [a now non-standard place](https://github.com/sleepdiary/library/tree/main/doc) - another one for the todo list).

I'm happy to *support* developers who want to run `yarn` outside of a container, but I'm in two minds about *advertising* it.  You know the case in favour better than me, so I'll stick to the case against...

For the purpose of this discussion, we can split developers into two groups - those who are already familiar with the node ecosystem, and those who aren't.  Those who are familiar with node will probably see `package.json` and get to work without reading the documentation (or like you, will read it and disregard it).  That's fine, but it means the documentation isn't for them.  People who aren't familiar with node - and especially new developers who are overwhelmed by the whole development process - need simple instructions they can't mess up.  Or to put a finer point on it, that they can only mess up in ways that are easy to diagnose when they ask for help.

Docker guarantees that simplicity across the whole project, even if we add more repositories in future that don't use node at all.  Describing two build processes for every project seems like a recipe for trouble.

Having said all of that, how would you feel about adding a line something like:

> If you prefer not to use the `Dockerfile`, see [the instructions for running vue apps](https://cli.vuejs.org/guide/cli-service.html)

The exact text would need to be cleared up, but linking to another location should make it clear that it's a supported alternative, without promising to help if you mess up in some weird way.

By the way, thanks for looking through all this.  I'm not sure if it comes across, but even when we've disagreed about stuff, I generally walk away looking for new ways to tackle the problems you bring up.

**Comment by andrew-sayers** [comment]
By the way, a quick but important question...

I'm thinking about changing the copyright attribution from "Andrew Sayers" to something that reflects that it's a team project now.  I guess "sleepdiary team" is the obvious choice.  Do you have any strong opinions about that sort of thing?  "No" is a fine answer, but I'll hold off on your PRs in case it's a yes.

**Comment by quinn-dev** [comment]
I'll start with the last question, since that's probably the easiest one. If it's a team project, I think changing the copyright attribution appropriately makes sense. Generally speaking, I'm unsure what purpose the copyright attribution in the license serves, as it does not serve as a CLA and each contributor retains copyright for their contributed code. But legal considerations aside, I think something like "sleepdiary team" or just "sleepdiary" is both more representative and makes the project easier to find (if that's a concern).

Moving on to Docker - I think we have two different audiences in mind: I was mostly thinking about JavaScript developers who want to get started with development quickly and would be rather confused when prompted to run everything in a Docker container. Your focus on the other hand seems to be on less experienced people who simply want to compile the web app or launch a web server. For these people, Docker instructions do make a lot more sense than requiring them to install node and yarn. And in the context of this particular project - a dashboard primarily used by end users who aren't required to have any technical experience whatsoever - I agree that the focus should lie on making the instructions as beginner-friendly as possible. To that end, I'd consequently propose having a short requirements section so that people who don't have any prior Docker experience can get up & running.

As for non Docker-related instructions: I do think that a short notice stating that Docker is not a requirement would be helpful, especially for development. A look at the `project.json` doesn't reveal whether a project requires Docker and in order to determine whether it does, you need to understand how Docker works. Perhaps there could be a separate `DEVELOPMENT.md` detailing both Docker and non-Docker workflows.

To make my intentions a bit more transparent: I do use and like Docker, but I think plenty of JS / Vue developers have never really used Docker (other than copy-pasting a command) and it would be worthwhile to point out to potential contributors that Docker knowledge is not a prerequisite for this project and that they can contribute using the "standard" workflow.

I understand your reasons for doing these things your way more clearly with every issue. I also hope I don't come across as too nitpicky by focusing primarily on things like development processes. Your style is very, very different from the rest of the JavaScript ecosystem (no node, no modern, fancy tooling, etc.) and I sometimes find it difficult at first to understand why you do the things you do the way you do.

**Comment by andrew-sayers** [comment]
I went with "Sleepdiary Developers" in the end.  It's not impossible we could end up with translators or something in future, who would be part of the "team" but their copyright would be for the translations rather than the codebase.  I've also pushed out some commits across the project.

Would you like the project to have a CLA?  I'm not sure the best balance between giving people certainty about legal issues vs. wrapping them up in red tape, and frankly you're in a better place to judge this than i am.  If so, please open a new issue and we'll work something out.

This conversation is starting to meander a bit, so I'm trying out GitHub's fancy new discussions feature.  I guess you've been notified already, but for the sake of people reading - see [Scope and name of different repositories](https://github.com/sleepdiary/sleepdiary.github.io/discussions/1) and [How best to support other developers](https://github.com/sleepdiary/sleepdiary.github.io/discussions/2).

I think the issues discussed here have either been dealt with or are better addressed elsewhere, so I'm going to close this for now.  Feel free to reopen it if there's something relevant here that isn't covered there.

**Comment by quinn-dev** [comment]
I will just briefly respond to the CLA question here since it doesn't fit in with the other discussions: I would be very opposed to a CLA. All I wanted to do is point out that, regardless of who is attributed in the LICENSE, individual contributors retain their copyright unless they sign a CLA. This does not create legal uncertainty - the code can be used in any way the license permits. Having multiple developers with copyright claims to parts of the code has one substantial advantage: Any developer who contributed in a meaningful way could litigate license violations, for example if a company decided to use the library without open-sourcing their code.

As an example for why I think CLAs aren't appropriate for open-source projects: Audacity recently introduced a new [privacy policy](https://github.com/audacity/audacity/issues/1213) which directly violated their GPLv3 license. To circumvent the license, they made most core contributors sign a CLA, hoping they could change the license retroactively to remove the protections it guarantees.

Other questions regarding the license may deserve their own issues, but I personally think GPLv2 is a good choice.
