### ISSUE TITLE
time zone error? attempting to load Sleepmeter file

### ISSUE THREAD

**Issue by insipidlight** [sleepdiary/dashboard#83]
**Describe the bug**
`An error occurred
Something went wrong with the app.
Please report the issue so we can fix it.
[ [ "0", [ "stack", "timezonecomplete.InvalidTimeZoneData: Rule Mexico[0][3] is not a month name []\n at Object.throwError (https://cdn.jsdelivr.net/npm/timezonecomplete@5.12.x/dist/timezonecomplete.min.js:1:49747)\n at https://cdn.jsdelivr.net/npm/timezonecomplete@5.12.x/dist/timezonecomplete.min.js:1:124219\n at new TzDatabase (https://cdn.jsdelivr.net/npm/timezonecomplete@5.12.x/dist/timezonecomplete.min.js:1:125875)\n at TzDatabase.init (https://cdn.jsdelivr.net/npm/timezonecomplete@5.12.x/dist/timezonecomplete.min.js:1:126812)\n at TzDatabase.instance (https://cdn.jsdelivr.net/npm/timezonecomplete@5.12.x/dist/timezonecomplete.min.js:1:126908)\n at Ba (https://sleepdiary.github.io/core/sleepdiary-core.min.js:50:44)\n at Z.daily_activities (https://sleepdiary.github.io/core/sleepdiary-core.min.js:98:255)\n at y (https://sleepdiary.github.io/dashboard/js/info.3b696c1e.worker.js:1:10647)\n at Fa.success_callback (https://sleepdiary.github.io/dashboard/js/info.3b696c1e.worker.js:1:10111)\n at Fa.load (https://sleepdiary.github.io/core/sleepdiary-core.min.js:59:378)" ] ], [ "1", [ "message", "Rule Mexico[0][3] is not a month name []" ] ], [ "2", [ "name", "timezonecomplete.InvalidTimeZoneData" ] ], [ "length", 3 ] ]`

**To Reproduce**
1. Add new file, select file picker

**Smartphone:**
 - Device: Pixel
 - OS: Android 14
 - Browser: Microsoft Edge
 - Version: Edge 128.0.2739.82

**Comment by insipidlight** [comment]
Same error happens on Firefox, and with the example scenarios

**Comment by andrew-sayers** [comment]
Thanks for letting me know.  I've [sent a PR upstream](https://github.com/rogierschouten/tzdata-generate/pull/16), and will look into a workaround if there's no satisfactory response in the next few days.

The workaround would mean reverting to an earlier version of the upstream library, and I'm concerned about making a mistake given how long it's been since I last worked on this repo.  Not worth the risk if they roll out a proper fix tomorrow morning, but definitely worth the risk if they plan to take a few months.

Background if you're interested: the dashboard ultimately gets dates from [the IANA tzdata database](https://www.iana.org/time-zones).  The 2024b update was released on September 4th, and includes a timezone change for Mexico in "April" of 1931.  "April" is abbreviated to "Apr" everywhere else in the database, and we use the "timezonecomplete" library, which only expects to see "Apr".  Hence the message `"timezonecomplete.InvalidTimeZoneData: Rule Mexico[0][3] is not a month name`.

**Comment by andrew-sayers** [comment]
They rolled out a proper fix yesterday evening :)

You may need to force-refresh your browser, if it hasn't updated itself automatically yet.  Feel free to reopen this bug if it's still not working.
